services:
  moonbite:
    command: ['sleep', 'infinity']
    volumes:
      - bashhistory:/commandhistory
      - claude-config:/home/node/.claude
      - ~/.gitconfig:/home/node/.gitconfig:rw
      - ~/.ssh:/home/node/.ssh:rw

volumes:
  bashhistory:
  claude-config:
